# Generated by Django 3.2.3 on 2021-05-15 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truestcaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number should start from 6 to 9 and must contain 10 digits.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
